baseURL = "https://zlink.github.io/"
title = "Zlink"
languageCode = "zh-cn"
theme = "m10c"
paginate = 10

[params]
  author = "Zlinkä¸¶"
  avatar = "images/avatar.jpg"
  description = "Just do it."
  [[params.social]]
    name = "github"
    url = "https://github.com/zlink"
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/zlink/"